version: "3"
services:
  embress:
    image: meidlinger1024/embress:latest
    container_name: embress
    restart: always
    ports:
      - "15000:15000"
    volumes:
      - D:\Code\Tools\embress\data\media\A:/app/media/path1
      - D:\Code\Tools\embress\data\logs:/app/python/logs
      - D:\Code\Tools\embress\data\conf:/app/conf
    environment:
      - TZ=Asia/Shanghai
      - ACCESS_KEY=ACCESS_KEY
      - MEDIA_PATH=/app/media
      - CONFIG_DB_PATH=/app/conf/config.db
      - LOG_PATH=/app/python/logs
      - SCAN_INTERVAL=3600